mysql:
  dns: root:791975457@qq.com@tcp(127.0.0.1:3306)/ginchat?charset=utf8mb4&parseTime=True&loc=Local

redis:
  addr: "39.104.17.28:6379"
  password: "791975457@qq.com"
  DB: 0
  poolSize: 30
  minIdleConn: 30
